import Head from "next/head";
import Image from "next/image";
import Hero from "../components/hero";
import Values from "../components/values";
import Teachers from "../components/teachers";
import Students from "../components/students";
import Moreinfo from "../components/moreinfo";
import Trial from "../components/trial";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ed -Circle Education Website</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Values/>
      <Teachers/>
      <Students/>
      <Moreinfo/>
      <Trial/>
      <Footer/>
    </div>
  );
}
